
require File.expand_path( './lib/base.rb', File.dirname(__FILE__)  )
require File.expand_path( './lib/inflections.rb', File.dirname(__FILE__))
require File.expand_path( './lib/string.rb', File.dirname(__FILE__))
require File.expand_path( './lib/math.rb', File.dirname(__FILE__))
autoload :AngularRailsBuilder, File.expand_path( './lib/angular_rails.rb', File.dirname(__FILE__))
autoload :RestAngularBuilder, File.expand_path( './lib/restangular.rb', File.dirname(__FILE__))
autoload :RestAngularModalBuilder, File.expand_path( './lib/restangular_modal.rb', File.dirname(__FILE__))
autoload :RailsBuilder, File.expand_path( './lib/rails.rb', File.dirname(__FILE__))
autoload :RailsVanillaBuilder, File.expand_path( './lib/rails_vanilla.rb', File.dirname(__FILE__))
autoload :RSpecBuilder, File.expand_path( './lib/rspec.rb', File.dirname(__FILE__))
autoload :CucumberBuilder, File.expand_path( './lib/cucumber.rb', File.dirname(__FILE__))
autoload :CoffeeBuilder, File.expand_path( './lib/coffee.rb', File.dirname(__FILE__))
autoload :UIrouterBuilder, File.expand_path( './lib/ui_router.rb', File.dirname(__FILE__))
autoload :MeanBuilder, File.expand_path( './lib/mean.rb', File.dirname(__FILE__))
